#!/usr/bin/env python3
import os
import sys

def main(path: str, win: str):
    win = win.replace(os.environ['HOME'], '~')
    if '...' not in win and '/' not in win:
        print(win)
        return

    raw_parts = path.replace(os.environ['HOME'], '~').split('/')
    parts = []
    last_part_l = 0
    for i, p in enumerate(raw_parts):
        if i == len(raw_parts) - 1:
            parts.append(p)
            last_part_l = len(p)
        else:
            parts.append(p[0] if len(p) > 0 else "")

    m = max(last_part_l, 16)
    if m == last_part_l:
        print(parts[-1])
        return

    out = ""
    for i, p in enumerate(parts):
        out += p
        if i < len(parts) - 1:
            out += "/"
    print(out if len(out) < m else f"{out[-m:]}")

if __name__ == '__main__':
    main(*sys.argv[1:])
