#!/usr/bin/env bash

prog="$1"

if [ -z "$prog" ]; then
    echo usage "$0": prog
    exit 1
fi

case "$prog" in
    rust|cargo                      ) echo -n "" ;;
    go                              ) echo -n "" ;;
    zsh|bash|sh|nu                  ) echo -n "" ;;
    vim|vimdiff                     ) echo -n "" ;;
    nvim                            ) echo -n "" ;;
    hx|zk                           ) echo -n "" ;;
    swipl                           ) echo -n "" ;;
    man|glow*                       ) echo -n "" ;;
    rizin                           ) echo -n "󱁆" ;;
    gdb|rr                          ) echo -n "" ;;
    bat                             ) echo -n "" ;;
    *python*|pip[23]                ) echo -n "" ;;
    meson|cmake|make|ninja          ) echo -n "" ;;
    kubectl|k9s                     ) echo -n "󱃾" ;;
    docker*                         ) echo -n "" ;;
    vagrant                         ) echo -n "" ;;
    sqlite*                         ) echo -n "" ;;
    *mysql*                         ) echo -n "" ;;
    *postgres*                      ) echo -n "" ;;
    git*                            ) echo -n "" ;;
    gh                              ) echo -n "" ;;
    *top                            ) echo -n "" ;;
    *pdf*|zathura|okular            ) echo -n "" ;;
    lynx|w3m                        ) echo -n "" ;;
    ssh|mosh*|lima*                 ) echo -n "" ;;
    scheme|petite                   ) echo -n "λ" ;;
    ghc*|stack                      ) echo -n "" ;;
    nnn|vifm                        ) echo -n "" ;;
    *emacs*                         ) echo -n "" ;;
    julia                           ) echo -n "" ;;
    ruby                            ) echo -n "" ;;
    node*|npm                       ) echo -n "" ;;
    delta                           ) echo -n "∆" ;;
    packer                          ) echo -n "" ;;
    mpv                             ) echo -n "" ;;
    spt                             ) echo -n "" ;;
    pomodoro                        ) echo -n "🍅" ;;
    *                               ) echo -n "" ;;
esac
