#!/usr/bin/env bash

prog="$1"

if [ -z "$prog" ]; then
    echo usage "$0": prog
    exit 1
fi

case "$prog" in
    *emacs*                         ) echo -n "" ;;
    *mysql*                         ) echo -n "" ;;
    *pdf*|okular|zathura            ) echo -n "" ;;
    *postgres*                      ) echo -n "" ;;
    *python*|pip[23]                ) echo -n "" ;;
    *top                            ) echo -n "" ;;
    argocd                          ) echo -n "" ;;
    bash|nu|sh|zsh                  ) echo -n "" ;;
    bat                             ) echo -n "󰈮" ;;
    brew                            ) echo -n "" ;;
    cargo|rust                      ) echo -n "" ;;
    claude|opencode                 ) echo -n "" ;;
    cmake|just|make|meson|ninja     ) echo -n "" ;;
    crush                           ) echo -n "" ;;
    delta                           ) echo -n "∆" ;;
    docker*                         ) echo -n "" ;;
    gdb|rr                          ) echo -n "" ;;
    gh                              ) echo -n "" ;;
    ghc*|stack                      ) echo -n "" ;;
    git*                            ) echo -n "" ;;
    glow*|man                       ) echo -n "" ;;
    go                              ) echo -n "" ;;
    hours                           ) echo -n "󰔛" ;;
    hx|zk                           ) echo -n "" ;;
    julia                           ) echo -n "" ;;
    k9s|kubectl                     ) echo -n "󱃾" ;;
    lima*|mosh*|ssh                 ) echo -n "" ;;
    lynx|w3m                        ) echo -n "" ;;
    nnn|vifm                        ) echo -n "" ;;
    node*|npm                       ) echo -n "" ;;
    nvim                            ) echo -n "" ;;
    packer                          ) echo -n "" ;;
    petite|scheme                   ) echo -n "λ" ;;
    podman*                         ) echo -n "" ;;
    pomodoro                        ) echo -n "🍅" ;;
    rizin                           ) echo -n "󱁆" ;;
    ruby                            ) echo -n "" ;;
    spt                             ) echo -n "" ;;
    sqlite*                         ) echo -n "" ;;
    swipl                           ) echo -n "" ;;
    vagrant                         ) echo -n "" ;;
    vim*                            ) echo -n "" ;;
    *                               ) echo -n "" ;;
esac
