#!/usr/bin/env bash

set -eu

# get data either form stdin or from file
buf=$(cat "$@")

# Get buffer length
buflen=$(echo -n "$buf" | wc -c)

maxlen=74994

# warn if exceeds maxlen
if [ "$buflen" -gt "$maxlen" ]; then
    echo "input is $((buflen - maxlen)) bytes too long" >&2
fi

# build up OSC 52 ANSI escape sequence
esc="\033]52;c;$(echo -n "$buf" | head -c $maxlen | base64 | tr -d '\r\n')\a"
esc="\033Ptmux;\033$esc\033\\"

# grab active pane tty
pane_active_tty=$(tmux list-panes -F "#{pane_active} #{pane_tty}" | awk '$1=="1" { print $2 }')
target_tty="${SSH_TTY:-$pane_active_tty}"

echo -en "$esc" >"$target_tty"
