#!/usr/bin/env bash

set -e

# Set defaults for environments that call this script directly (e.g. dev containers, codespaces)
export DOTFILES_IS_LIGHTWEIGHT=${DOTFILES_IS_LIGHTWEIGHT:-1}
export DOTFILES_WITH_APPS=${DOTFILES_WITH_APPS:-0}
export DOTFILES_WITH_ASDF=${DOTFILES_WITH_ASDF:-0}
export DOTFILES_WITH_BREW=${DOTFILES_WITH_BREW:-0}
export DOTFILES_WITH_LSP=${DOTFILES_WITH_LSP:-0}
export DOTFILES_WITH_VIRT=${DOTFILES_WITH_VIRT:-0}

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
