theme = "base16-outrun-dark"

[editor]
line-number = "relative"
cursorline = true
text-width = 100
rulers = [100]
true-color = true

[editor.whitespace]
render = "all"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
