[settings]
disable_backends = ["asdf", "vfox"]
install_before = "7d"
lockfile = true

[tools]
atuin = "latest"
bat = "latest"
bun = "latest"
devcontainer-cli = "latest"
fd = "latest"
go = "latest"
lsd = "latest"
lua-language-server = "latest"
node = "24"
perl = "latest"
ripgrep = "latest"
ruff = "latest"
shellcheck = "latest"
shfmt = "latest"
starship = "latest"
stylua = "latest"
ty = "latest"
zoxide = "latest"
