[settings]
disable_backends = ["asdf", "vfox"]
minimum_release_age = "7d"
lockfile = true

[tools]
atuin = "latest"
bat = "latest"
fd = "latest"
lsd = "latest"
ripgrep = "latest"
starship = "latest"
zoxide = "latest"
