def has?(s)
    ENV["DOTFILES_#{s}"] == "1" || system("[ -f ~/.config/dotfiles-env/#{s.downcase} ]")
end

IS_DARWIN       = system "[ $(uname) = Darwin ]"
IS_LIGHTWEIGHT  = has? :IS_LIGHTWEIGHT
WITH_APPS       = has? :WITH_APPS
WITH_ASDF       = has? :WITH_ASDF
WITH_LSP        = has? :WITH_LSP
WITH_VIRT       = has? :WITH_VIRT

tap "homebrew/core"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"

# Applications
cask "amethyst"                 if WITH_APPS && IS_DARWIN
cask "firefox"                  if WITH_APPS && IS_DARWIN
cask "grandperspective"         if WITH_APPS && IS_DARWIN
brew "mpv"                      if WITH_APPS
cask "obs"                      if WITH_APPS
cask "obsidian"                 if WITH_APPS && IS_DARWIN
cask "owncloud"                 if WITH_APPS && IS_DARWIN
cask "slack"                    if WITH_APPS && IS_DARWIN
cask "spotify"                  if WITH_APPS && IS_DARWIN
cask "zoom"                     if WITH_APPS && IS_DARWIN
cask "zotero"                   if WITH_APPS && IS_DARWIN

# Fonts
cask "font-hack-nerd-font"      if IS_DARWIN

# Hardware support
cask "1kc-razer"                if IS_DARWIN

# Programming
brew "efm-langserver"           if WITH_LSP
brew "gopls"                    if WITH_LSP
brew "rust-analyzer"            if WITH_LSP
brew "shellcheck"
brew "shfmt"
cask "visual-studio-code"       if WITH_APPS && IS_DARWIN
brew "universal-ctags"

# Terminal
brew "alacritty"                if WITH_APPS
brew "atuin"
brew "bat"
brew "chafa"
brew "dust"
brew "fd"
brew "figlet"
brew "fzf"
brew "gawk"
brew "git-delta"
brew "htop"
brew "jless"
brew "jq"
brew "lynx"
brew "neofetch"
brew "neovim"                   unless IS_LIGHTWEIGHT
brew "nnn"
brew "nushell"
brew "pandoc"                   unless IS_LIGHTWEIGHT
brew "pastel"
brew "ripgrep"
brew "spotify-tui"              if WITH_APPS
brew "starship"
brew "thefuck"
brew "tmux"
brew "tree"
brew "vgrep"
brew "vifm"
brew "wakeonlan"
brew "zoxide"

# TeX
cask "mactex-no-gui"            if IS_DARWIN

# Virtualization / emulation
if WITH_VIRT
    cask "docker"               if IS_DARWIN
    brew "libvirt"
    brew "podman"
    brew "qemu"
    cask "utm"                  if IS_DARWIN
end

if WITH_ASDF
    # asdf nodejs
    brew "gpg"
    # asdf ruby
    brew "openssl"
    brew "readline"
end
