#!/usr/bin/env python3

import argparse
import math
import sys

parser = argparse.ArgumentParser(description="Convert ANSI 256-colors to RGB")
parser.add_argument("color", type=int, help="the color to convert")
parser.add_argument("-q", "--quiet", action="store_true", default=False,
                    help="only print converted color, if any")
args = parser.parse_args()

def die(s):
    if not args.quiet:
        print(s, file=sys.stderr)
    sys.exit(1)

if args.color < 0:
    die("Color to convert must be non-negative")
elif args.color < 16:
    die("Cannot convert standard colors (i.e. [0, 15])")
elif args.color > 231:
    die("Cannot convert grayscale colors (i.e. [232, 255])")

scale = 255 / 5
code = 1
for b in range(6):
    for g in range(6):
        for r in range(6):
            c256 = 16 + 36*r + 6*g + b
            if c256 != args.color:
                continue
            rgb = (math.ceil(r * scale) << 16) | \
                  (math.ceil(g * scale) << 8)  | \
                   math.ceil(b * scale)
            print(c256, '=', hex(rgb))
            code = 0

sys.exit(code)
