#!/usr/bin/env python3
"""Setup auxiliary files for tools installed by mise, like shell completions."""

import json
import os
import platform
import shlex
import shutil
import subprocess
from typing import NotRequired, TypedDict, assert_never

match os.path.basename(os.environ["SHELL"]):
    case "zsh":
        SHELL = "zsh"
        FPATH = os.path.join(os.environ["HOME"], ".local", "share", "mise-aux")
    case shell:
        raise RuntimeError(f"Unexpected SHELL={shell}")


class MiseSource(TypedDict):
    type: str
    path: str


class MiseVersion(TypedDict):
    version: str
    install_path: str
    installed: bool
    active: bool
    requested_version: NotRequired[str]
    source: NotRequired[MiseSource]


def _run(*cmd: str) -> str:
    print("running:", shlex.join(cmd))
    r = subprocess.run(cmd, capture_output=True, text=True)
    try:
        r.check_returncode()
    except subprocess.SubprocessError:
        print(f"Error: {r.stderr}")
        raise
    return r.stdout


def _completion(tool: str, script: str) -> None:
    if not os.path.exists(FPATH):
        print(f"mkdir: {FPATH}")
        os.mkdir(FPATH)

    match SHELL:
        case "zsh":
            p = os.path.join(FPATH, "_" + tool)
        case _:
            assert_never(SHELL)

    print(f"writing: {tool} -> {p} ({len(script)})")
    with open(p, "w") as f:
        f.write(script)
    os.chmod(p, 0o755)


def _copy_completion(tool: str, src: str) -> None:
    match SHELL:
        case "zsh":
            dst = os.path.join(FPATH, "_" + tool)
        case _:
            assert_never(SHELL)
    print(f"copying: {tool} {src!r} -> {dst!r}")
    shutil.copy(src, dst)


def _mise_ls() -> dict[str, list[MiseVersion]]:
    r = _run("mise", "ls", "--current", "--json")
    d = json.loads(r)
    for k in d.keys():
        d[k] = [MiseVersion(**v) for v in d[k]]
    return d


def atuin(_v: MiseVersion) -> None:
    r = _run("atuin", "gen-completions", "--shell", SHELL)
    _completion("atuin", r)


def bat(_v: MiseVersion) -> None:
    r = _run("bat", "--completion", SHELL)
    _completion("bat", r)


def fd(_v: MiseVersion) -> None:
    r = _run("fd", "--gen-completions", SHELL)
    _completion("fd", r)


def lsd(v: MiseVersion) -> None:
    match machine := platform.machine():
        case "arm64":
            machine = "aarch64"
    match system := platform.system():
        case "Darwin":
            system = "apple-darwin"
    match SHELL:
        case "zsh":
            src = os.path.join(
                v["install_path"],
                f"lsd-v{v['version']}-{machine}-{system}",
                "autocomplete",
                "_lsd",
            )
        case _:
            assert_never(SHELL)
    _copy_completion("lsd", src)


def ripgrep(_v: MiseVersion) -> None:
    r = _run("rg", f"--generate=complete-{SHELL}")
    _completion("rg", r)


def starship(_v: MiseVersion) -> None:
    r = _run("starship", "completions", SHELL)
    _completion("starship", r)


def zoxide(v: MiseVersion) -> None:
    match SHELL:
        case "zsh":
            src = os.path.join(v["install_path"], "completions", "_zoxide")
        case _:
            assert_never(SHELL)
    _copy_completion("zoxide", src)


ls = locals()
pkgtrans = str.maketrans({c: "_" for c in ":-/"})
for pkg, versions in _mise_ls().items():
    fn_name = pkg.translate(pkgtrans)
    if (fn := ls.get(fn_name)) and callable(fn):
        fn(versions[0])
