#!/usr/bin/env perl
use strict;
use warnings;

my @ALL_COLORS = (
    "\e[0;31m",
    "\e[0;32m",
    "\e[0;33m",
    "\e[0;35m",
    "\e[0;36m",
    "\e[1;31m",
    "\e[1;32m",
    "\e[1;33m",
    "\e[1;34m",
    "\e[1;35m",
    "\e[1;36m",
);

my $color_i;
my %colors = ();
for(<<>>) {
    chomp;
    my ($time, $proto, $src, $dir, $dst) = /\A
            (\d{2}:\d{2}:\d{2}\.\d+)\s              # time
            ([A-Z]+)\s                              # networking proto?
            ([^\s]+)\s([<>])\s([^\s]+):             # source and destination
            /x
            or die "unrecognized !! $_";

    my $col = $colors{"$src $dst"} || $colors{"$dst $src"};
    if (!$col) {
        $color_i = ($color_i + 1) % @ALL_COLORS;
        $colors{"$src $dst"} = $ALL_COLORS[$color_i];
        $col = $colors{"$src $dst"};
    }

    print "$time $proto $col$src $dir $dst\e[0m:$'\n";
}
