#!/usr/bin/env python3
from os import environ
from shutil import which
from sys import argv, exit

def main(arg: str) -> bool:
    found_any = False
    for path in environ['PATH'].split(':'):
        if len(path) == 0:
            continue
        if path := which(arg, path=path):
            print(path)
            found_any = True
    return found_any

if __name__ == '__main__':
    if len(argv) < 2:
        print(f"usage: {argv[0]} name")
        exit(2)
    exit(not main(argv[1]))
