# shellcheck shell=bash

if [[ $- == *i* ]]; then
    set -o vi
    # shellcheck source=/dev/null
    source ~/.dotfiles/ble.sh/out/ble.sh
    IS_INTERACTIVE=1
fi

# source global definitions
# shellcheck source=/dev/null
[ -f /etc/bashrc ] && source /etc/bashrc
# shellcheck source=/dev/null
[ -f /etc/bash.bashrc ] && source /etc/bash.bashrc

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
if [ -z "$LESSOPEN" ] && [ -x /usr/bin/lesspipe ]; then
    eval "$(SHELL=/bin/sh lesspipe)"
fi

# add custom paths to PATH
if [[ -d "$HOME/.local/bin" && $PATH != *"$HOME/.local/bin:"* ]]; then
    PATH="$HOME/.local/bin:$PATH"
fi
if [[ -d "$HOME/.scripts" && $PATH != *"$HOME/.scripts:"* ]]; then
    PATH="$HOME/.scripts:$PATH"
fi
export PATH

export AWKPATH="$HOME/.awk:$AWKPATH"

# shellcheck source=shell/env.sh
source ~/.shell/env.sh

type atuin &>/dev/null && eval "$(atuin init bash --disable-up-arrow)"
type starship &>/dev/null && eval "$(starship init bash)"
type zoxide &>/dev/null && eval "$(zoxide init bash)"

# shellcheck source=shell/aliases.sh
source ~/.shell/aliases.sh
# shellcheck source=shell/functions.sh
source ~/.shell/functions.sh

[[ ${BLE_VERSION-} && $IS_INTERACTIVE = 1 ]] && ble-attach
unset IS_INTERACTIVE
